# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lp < Formula
  desc "k3s-on-podman local platform CLI: GitOps, Gateway API, local HTTPS"
  homepage "https://github.com/zaminda/local-platform"
  version "0.1.0"
  license "MIT"

  depends_on "helm"
  depends_on "k3d"
  depends_on "kubernetes-cli"
  depends_on "podman"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zaminda/local-platform/releases/download/v0.1.0/lp_darwin_amd64.tar.gz"
      sha256 "8c6b3ff1266446c21d16c7f8ec79a1deb4a3315546720fcf4624f4c4d797db2f"

      define_method(:install) do
        bin.install "lp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zaminda/local-platform/releases/download/v0.1.0/lp_darwin_arm64.tar.gz"
      sha256 "002b03d565584f3e117b3130ad036af536c1f38ded5f3eb37694b24cb357ff3c"

      define_method(:install) do
        bin.install "lp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zaminda/local-platform/releases/download/v0.1.0/lp_linux_amd64.tar.gz"
      sha256 "b4d65fb1070fee479f8300de93ad5f5dece135a9f00ae8b97bd4ba9671c181a1"
      define_method(:install) do
        bin.install "lp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zaminda/local-platform/releases/download/v0.1.0/lp_linux_arm64.tar.gz"
      sha256 "b7699345962b28c6e922af6a442acda2310364fb3318cdfc85ba286a1be9fe1b"
      define_method(:install) do
        bin.install "lp"
      end
    end
  end

  def caveats
    <<~EOS
      lp drives a local k3s cluster on podman. First time:
        podman machine init --memory 6144 --cpus 4
        podman machine start
      Then:
        lp cluster up && lp trust-ca
    EOS
  end
end
