# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lplat < Formula
  desc "k3s-on-podman local platform CLI: GitOps, Gateway API, local HTTPS"
  homepage "https://github.com/zaminda/local-platform"
  version "0.1.1"
  license "MIT"

  depends_on "helm"
  depends_on "k3d"
  depends_on "kubernetes-cli"
  depends_on "podman"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zaminda/local-platform/releases/download/v0.1.1/lplat_darwin_amd64.tar.gz"
      sha256 "5dcbdd52a86b765dba5150adebb1dff5e1ff9d5cf03fe62d0457f82842b19e18"

      define_method(:install) do
        bin.install "lplat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zaminda/local-platform/releases/download/v0.1.1/lplat_darwin_arm64.tar.gz"
      sha256 "f5e514912bc502056eba0cb5a417371495d0d2ee856478f62231351c7134b1ad"

      define_method(:install) do
        bin.install "lplat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zaminda/local-platform/releases/download/v0.1.1/lplat_linux_amd64.tar.gz"
      sha256 "c8b0883da969224fdf1e32a9ca4040daf349856ee7d4040b16725026388a470b"
      define_method(:install) do
        bin.install "lplat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zaminda/local-platform/releases/download/v0.1.1/lplat_linux_arm64.tar.gz"
      sha256 "7a8f7a12a59c4f0942e8765049bbe6b32dda111d62a9d597134ec4352eb2010c"
      define_method(:install) do
        bin.install "lplat"
      end
    end
  end

  def caveats
    <<~EOS
      lplat drives a local k3s cluster on podman. First time:
        podman machine init --memory 6144 --cpus 4
        podman machine start
      Then:
        lplat cluster up && lplat trust-ca
    EOS
  end
end
