# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pig < Formula
  desc "Simple TUI list picker"
  homepage "https://github.com/zaminda/pig"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zaminda/pig/releases/download/v0.1.1/pig_darwin_amd64.tar.gz"
      sha256 "23477ef93840e7f80d152d86817c8b928f86a2b47a200c8c59469da7a5516917"

      define_method(:install) do
        bin.install "pig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zaminda/pig/releases/download/v0.1.1/pig_darwin_arm64.tar.gz"
      sha256 "f90a761aaa7ef2678bd3873cc0a0ec7db222091f9dd25ac7de381c6a0ed3cc8c"

      define_method(:install) do
        bin.install "pig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zaminda/pig/releases/download/v0.1.1/pig_linux_amd64.tar.gz"
      sha256 "bcf7a3efecf5f1a454c8772a79bf07522679dae818a3a4300f3ee6edae1c3e87"
      define_method(:install) do
        bin.install "pig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zaminda/pig/releases/download/v0.1.1/pig_linux_arm64.tar.gz"
      sha256 "b8c6d729f8d76972670d0254ebe3e8de3c73ee24b8928a5f6ae5b592649bf0fe"
      define_method(:install) do
        bin.install "pig"
      end
    end
  end
end
