# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pig < Formula
  desc "Simple TUI list picker"
  homepage "https://github.com/zaminda/pig"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zaminda/pig/releases/download/v0.1.3/pig_darwin_amd64.tar.gz"
      sha256 "404bacfd8ee2cfae577d8cd50419cc2db12f7228382ab66d86c8fd8ae00b7b28"

      define_method(:install) do
        bin.install "pig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zaminda/pig/releases/download/v0.1.3/pig_darwin_arm64.tar.gz"
      sha256 "e916bde6760230f371e47ae2996edef297634914aaec9c64aade9c18fa23c3ca"

      define_method(:install) do
        bin.install "pig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zaminda/pig/releases/download/v0.1.3/pig_linux_amd64.tar.gz"
      sha256 "7e7defdca245b58925f580a24f9508e635be7687a45b202c76aead0456815a18"
      define_method(:install) do
        bin.install "pig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zaminda/pig/releases/download/v0.1.3/pig_linux_arm64.tar.gz"
      sha256 "150c2bafc68770292cd0c6e2e725a465423bf7eb9f755a05ce07a153f3a89b58"
      define_method(:install) do
        bin.install "pig"
      end
    end
  end
end
